### ISSUE TITLE
scrolling concepts

### ISSUE THREAD

**Issue by AlexImmer** [HPI-SWA-Teaching/SWT15-Project-09#42]
- [x] initial canvas size matches scroll pane size
- [ ] extend canvas by dropping classes near borders
- [ ] extend the canvas when the whole path view screen is resized

**Comment by AlexImmer** [comment]
Tests to write:

- [ ] center of scroller should equal center of scroll pane when initializing

**Comment by 01Track1mp3** [comment]
Things to consider when resizing:

- [ ] extend underlying scroller by difference in size, when the bounding box of class morphs is extended

**Comment by 01Track1mp3** [comment]
Constraints:

- Class Diagram Morph extent >= ScrollPane extent
